import os
import subprocess
from pathlib import Path
from typing import List, Optional
from models import DNSProfile, DNSType

class DNSManager:
    def __init__(self):
        self.config_path = Path("/etc/systemd/resolved.conf")
        self.backup_path = Path(f"/tmp/namban_resolved_backup_{os.getuid()}.conf")
        self.current_profile: Optional[DNSProfile] = None

    def backup_current_config(self) -> bool:
        try:
            if self.config_path.exists():
                subprocess.run(['pkexec', 'cp', str(self.config_path), str(self.backup_path)], check=True, capture_output=True)
                return True
        except subprocess.CalledProcessError:
            pass
        return False

    def restore_config(self) -> bool:
        try:
            if self.backup_path.exists():
                subprocess.run(['pkexec', 'mv', str(self.backup_path), str(self.config_path)], check=True, capture_output=True)
                self.reload_systemd_resolved()
                return True
        except subprocess.CalledProcessError:
            pass
        return False

    def apply_profile(self, profile: DNSProfile) -> bool:
        try:
            if not self.backup_current_config():
                pass
            config_content = self._generate_resolved_conf(profile)
            with subprocess.Popen(['pkexec', 'tee', str(self.config_path)], stdin=subprocess.PIPE, text=True,
                                  stdout=subprocess.DEVNULL, stderr=subprocess.PIPE) as process:
                _, stderr = process.communicate(input=config_content)
                if process.returncode != 0:
                    raise subprocess.CalledProcessError(process.returncode, 'tee', stderr=stderr)

            self.reload_systemd_resolved()
            self.current_profile = profile
            return True
        except Exception:
            self.restore_config()
            return False

    def _generate_resolved_conf(self, profile: DNSProfile) -> str:
        lines = ["# Generated by Namban DNS Manager", "[Resolve]"]
        dns_servers = []
        is_doh = any(s.dns_type == DNSType.DOH for s in profile.servers)
        is_dot = any(s.dns_type == DNSType.DOT for s in profile.servers)

        for server in profile.servers:
            dns_servers.append(server.primary)
            if server.secondary:
                dns_servers.append(server.secondary)

        if dns_servers:
            lines.append(f"DNS={' '.join(dns_servers)}")
        if is_doh:
            lines.append("DNSOverHTTPS=yes")
        elif is_dot:
            lines.append("DNSOverTLS=opportunistic")

        lines.extend(["DNSSEC=allow-downgrade", "DNSStubListener=yes", "Cache=yes", ""])
        return '\n'.join(lines)

    def reload_systemd_resolved(self):
        subprocess.run(['pkexec', 'systemctl', 'restart', 'systemd-resolved'], check=True, capture_output=True)

    def get_current_dns(self) -> List[str]:
        try:
            result = subprocess.run(['resolvectl', 'status'], capture_output=True, text=True, check=True)
            dns_servers = [line.split(':')[1].strip() for line in result.stdout.split('\n') if 'Current DNS Server:' in line]
            if not dns_servers:
                dns_servers = [s for line in result.stdout.split('\n') if 'DNS Servers:' in line for s in line.split(':')[1].strip().split()]
            return dns_servers
        except (subprocess.CalledProcessError, FileNotFoundError):
            return []
